version: '3'
services:
  react-app:
    image: kunalg3s/majorproject:client
    stdin_open: true
    ports:
      - '3000:3000'
    networks:
      - mern-app
  api-server:
    image: kunalg3s/majorproject:server
    ports:
      - '6500:6500'
    networks:
      - mern-app

  Elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    restart: always
    volumes:
    - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node    
      depends_on: 
          - api-server
    ports:
    - '9200:9200'
    - '9300:9300'
    networks:
      - mern-app

  Logstash:
    image: logstash:7.16.2
    container_name: logstash
    restart: always
    volumes:
    - ./logstash/:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf 
    depends_on:
      - Elasticsearch
    ports:
    - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"    
    networks:
      - mern-app

  Kibana:
    image: kibana:7.16.2
    container_name: kibana
    restart: always       
    ports:
    - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200  
    depends_on:
      - Elasticsearch  
    networks:
      - mern-app
volumes:
  elastic_data: {}

networks:
  mern-app:
    driver: bridge