version: "3"
services:
  react-app:
    image: kunalg3s/majorproject:client
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    image: kunalg3s/majorproject:server
    ports:
      - "6500:6500"
    networks:
      - mern-app

  networks:
   mern-app:
     driver: bridge
 

  